sonar.projectKey=CRM-PFE
sonar.projectName=CRM-PFE
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=Projet_flutter/lib,Projet_flutter_backend/src

sonar.exclusions=**/build/**,**/.dart_tool/**,**/ios/**,**/android/**,**/linux/**,**/windows/**,**/macos/**,**/web/**

# Couverture des tests Backend (Jest)
sonar.javascript.lcov.reportPaths=Projet_flutter_backend/coverage/lcov.info

# Couverture des tests Flutter (si plugin Dart installé)
sonar.dart.lcov.reportPaths=Projet_flutter/coverage/lcov.info